config/routes.rb
Rails.application.routes.draw do
  resources :orders


  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :users
  resources :products do
    resources :orders
  end
  resources :profiles
  resources :charges

  # as :user do
  #   get '/profile' => 'users/registrations#edit', as: 'edit_user_registration'
  #   patch '/profile' => 'users/registrations#update'
  # end

  get "home/index"
  # get 'market', to: => 'products#index', as: => 'market'

  get '/profile', to:  'profile#index', as: 'user_profile'
  get '/dashboard', to:  'dashboard#index', as: 'dashboard'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

before_action :authenticate_user!
before_action :check_user

  def index
    @user = current_user
    @products = Product.where(user: current_user)
  end

  def check_user
    unless current_user.has_role?(:bcmember)
      redirect_to root_url, alert: "Sorry, you do not have access to this content."
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_sidenav.html.erb
<div class="column is-3">
<% if current_user.has_role? :bcmember %>
  <aside class="menu">
    <p class="menu-label">
      General
    </p>
    <ul class="menu-list">
      <li>
        <%= link_to 'Dashboard', dashboard_path %>
      </li>
    </ul>
    <p class="menu-label">
      Administration
    </p>
    <ul class="menu-list">
      <li>
        <a>Store Settings</a>
      </li>
      <li>
        <%= link_to 'Account Settings', user_profile_path %>
      </li>
      <li>
        <a>Manage Your Products</a>
        <ul>
          <li>
            <a>View Products</a>
          </li>
          <li>
            <%= link_to 'List Product', new_product_path %>
          </li>
        </ul>
      </li>
    </ul>
    <p class="menu-label">
      Transactions
    </p>
    <ul class="menu-list">
      <li>
        <a>Orders</a>
      </li>
      <li>
        <a>Payments</a>
      </li>
      <li>
        <a>History</a>
      </li>
    </ul>
  </aside>
  <% else %>
  <aside class="menu">
    <p class="menu-label">
      General
    </p>
    <ul class="menu-list">
      <li>
        <%= link_to 'Account Settings', user_profile_path %>
      </li>
    </ul>
    <p class="menu-label">
      Transactions
    </p>
    <ul class="menu-list">
      <li>
        <a>Orders</a>
      </li>
      <li>
        <a>Payments</a>
      </li>
      <li>
        <a>History</a>
      </li>
    </ul>
  </aside>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

  <div class="container">
    <div class="columns">
      <%= render 'dashboard/sidenav' %>
      <div class="column is-9">
        <section class="hero is-transparent welcome is-small">
          <div class="hero-body">
            <div class="container">
              <h1 class="title">
                Hello, <%= current_user.username %>.
              </h1>
              <h2 class="subtitle">
                Welcome to your BIOS Collective Store!
              </h2>
            </div>
          </div>
        </section>
        <%# <section class="info-tiles">
          <div class="tile is-ancestor has-text-centered">
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title">0</p>
                <p class="subtitle">Products</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title">0</p>
                <p class="subtitle">Sales</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title">0</p>
                <p class="subtitle">Open Orders</p>
              </article>
            </div>
            <div class="tile is-parent">
              <article class="tile is-child box">
                <p class="title">0</p>
                <p class="subtitle">Messages</p>
              </article>
            </div>
          </div>
        </section> %>
        <div class="columns">
          <div class="column is-6">
            <div class="card events-card">
              <header class="card-header">
                <p class="card-header-title">
                  Your Products
                </p>
                <a href="#" class="card-header-icon" aria-label="more options">
                  <span class="icon">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                  </span>
                </a>
              </header>
              <div class="card-table">
                <div class="table-container">
                  <table class="table is-fullwidth">
                    <tbody>
                      <% @products.each do |product| %>
                      <tr>
                        <td width="5%">
                          <i class="fa fa-bell-o"></i>
                        </td>
                        <td><%=  link_to product.name, product %></td>
                        <td>
                          <div class="buttons has-addons is-pulled-right">
                          <%= link_to 'View', product, class: "button is-small is-black" %>
                          <%= link_to 'Edit', edit_product_path(product), class: "button is-small is-black" %>
                          <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-small is-black" %>
                          </div>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
              <footer class="card-footer">
                <a href="#" class="card-footer-item">View All</a>
              </footer>
            </div>
          </div>
          <div class="column is-6">
            <div class="card">
              <header class="card-header">
                <p class="card-header-title">
                  Inventory Search
                </p>
                <a href="#" class="card-header-icon" aria-label="more options">
                  <span class="icon">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                  </span>
                </a>
              </header>
              <div class="card-content">
                <div class="content">
                  <div class="control has-icons-left has-icons-right">
                    <input class="input is-small" type="text" placeholder="">
                    <span class="icon is-medium is-left">
                      <i class="fa fa-search"></i>
                    </span>
                    <span class="icon is-medium is-right">
                      <i class="fa fa-check"></i>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>