config/routes.rb
Rails.application.routes.draw do
  resources :orders


  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :users
  resources :products do
    resources :orders
  end
  resources :profiles
  resources :charges

  # as :user do
  #   get '/profile' => 'users/registrations#edit', as: 'edit_user_registration'
  #   patch '/profile' => 'users/registrations#update'
  # end

  get "home/index"
  # get 'market', to: => 'products#index', as: => 'market'

  get '/profile', to:  'profile#index', as: 'user_profile'
  get '/dashboard', to:  'dashboard#index', as: 'dashboard'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :set_amount

  after_action :send_email, only: [:create]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @product = Product.find(params[:product_id])
    @amount = (@product.price * 100).floor
    @seller = @product.user

   

    @order.product_id = @product.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        # OrderMailer.send_order_email(@user).deliver
        format.html { redirect_to products_path, notice: 'Order was successfully submitted.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  customer = nil
  if current_user.stripe_customer_id.present?
    customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
  else
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :source => params[:stripeToken],
      :shipping => {
        :address => {
          :line1 => current_user.address['street_address'],
          :city => current_user.address['city'],
          :state => current_user.address['state'],
          :postal_code => current_user.address['postcode'],
          :country => current_user.address['country'],
        },
        :name => current_user.first_name + " " + current_user.last_name,
      }
    )
  end

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount, #in cents
      :description => @product.name,
      :currency => 'aud'
    )

    current_user.update_attributes(stripe_customer_id: customer.id)
    # rescue Stripe::CardError => e
    #   flash[:error] = e.message
    #   redirect_to new_order_path
    # end

    # private
    # def set_amount
    #   @amount = product.price
    # end

  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.permit(:product_id, :buyer_id, :seller_id)
    end

    # def set_amount
    #   @amount = @product.price
    # end

    def send_email
      OrderMailer.send_order_email(current_user).deliver
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="container">
<div class="columns is-centered">
<div class="column is-4">
<%= form_with(model: [@product, @order], url: product_orders_path, local: true, id: "payment-form") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <label><%= @product.name %></label>
    <label>$<%= @product.price %></label>
    <br>
    <label for="card-element" class="label">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors"></div>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"button", value:"Submit" %>&ensp;<%= link_to 'Back', product_orders_path, class:"button"%>
  </div>
<% end %>

</div>
</div>
</div>

<script type="text/javascript">

  var stripe = Stripe('pk_test_vLKKXrOAgZLbbQMxILVsPrNw');
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  var style = {
    base: {
      // Add your base input styles here. For example:
      fontSize: '16px',
      color: "#32325d",
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  // Create a token or display an error when the form is submitted.
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the customer that there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }

</script>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Buyer</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_id %></td>
        <td><%= order.buyer_id %></td>
        <td><%= order.seller_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @order.product_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @order.seller_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>