config/routes.rb
Rails.application.routes.draw do
  resources :orders


  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :users
  resources :products do
    resources :orders
  end
  resources :profiles
  resources :charges

  # as :user do
  #   get '/profile' => 'users/registrations#edit', as: 'edit_user_registration'
  #   patch '/profile' => 'users/registrations#update'
  # end

  get "home/index"
  # get 'market', to: => 'products#index', as: => 'market'

  get '/profile', to:  'profile#index', as: 'user_profile'
  get '/dashboard', to:  'dashboard#index', as: 'dashboard'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  resourcify
  belongs_to :user
  has_many :orders

  mount_uploader :product_image, ProductImageUploader

  validates :name, :description, :price, presence: true
  validates :price, numericality: true, format: { with: /\A\$?[0-9]+\.?[0-9]?[0-9]?\z/, message: "Must be a dollar amount"}



  scope(:product_name, -> (name) { where("name like ?", "#{name}%")})
  # scope(:owner, -> (product_user) { where owner: @product_user})
  scope(:price, -> (price) { where price: price })

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    filtering_params(params).each do |key, value|
      @products = @products.public_send(key, value) if value.present?
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.owner = current_user.username

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :id, :price, :stock, :owner, :description, :product_image)
    end

    def check_user
      if current_user != @product.user
        redirect_to root_url, alert: "Sorry, this product does not belong to you"
      end
    end

    def filtering_params(params)
      params.slice(:product_name, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div class="notification">
      <button class="delete"></button>
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li> - <%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="label"><%= form.label :name %></label>
    <div class="control">
      <%= form.text_field :name, id: :product_name, class:"input", type:"text" %>
    </div>  
  </div>

  <div class="field">
    <label class="label"><%= form.label :price %></label>
    <div class="control">
      <%= form.text_field :price, id: :product_price, class:"input" %>
    </div>
  </div>

  <div class="field">
    <label class="label"><%= form.label :description %></label>
    <div class="control">
      <%= form.text_area :description, id: :product_description, class:"textarea", type:"text" %>
    </div>
  </div>

  <div class="field">
   <label class="label"><%= form.label :product_image %></label>
    <%= form.file_field :product_image %>
    <% if form.object.product_image? %>
      <%= image_tag form.object.product_image %>
      <%= form.label :remove_product_image %>
      <%= form.check_box :remove_product_image %> 
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class:"button"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
<div class="columns is-centered">
<div class="column is-3">
<h1 class="title is-4 has-text-centered">Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'View', @product %> |
<%= link_to 'Back', products_path %>
</div>
</div>
</div>

app/views/products/index.html.erb
<div class="container">
  <section class="hero is-black">
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          BIOS Collective Market
        </h1>
      </div>
    </div>
  </section>

  <section>
  <div class="columns is-mobile is-centered">
  <nav class="level">
  <%= form_tag(products_path, method: :get) do %>
    <div class="field is-horizontal">
    <div class="level-item">
      <div class="field-label is-normal">
        <label class="label"><%= label_tag 'product_name', 'Name:' %></label>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
          <%= text_field_tag 'product_name', nil, class: 'input is-small' %>
          </div>
        </div>
      </div>
    </div>
      &emsp;
      <div class="level-item">
      <div class="field-label is-normal">
        <label class="label"><%= label_tag 'price', 'Price:' %></label>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
          <%= text_field_tag 'price', nil, class: 'input is-small' %>
          </div>
        </div>
      </div>
      </div>
      &emsp;
      <div class="level-item">
      <%= submit_tag "Filter", class: 'button is-small' %>
      </div>
    </div>
    <% end %>
  </nav>
  </div>
  </section>

  <%# product cards %>
  <section>
    <div class="columns is-mobile is-multiline is-centered">
    <% @products.each do |product| %>
      <div class="column is-3">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag product.product_image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-5"><%=  link_to product.name, product %></p>
                <p class="subtitle is-6">$<%= product.price %></p>
              </div>
            </div>

            <div class="content">
              <%= product.description %>
              <br>
              <a>Created by <%= product.user.username %></a>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="columns">
    <%= render 'dashboard/sidenav' %>
    <div class="column is-3">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
<div class="columns is-centered">
<div class="column is-6">

<div class="card">
  <div class="card-image">
    <figure class="image">
      <%= image_tag @product.product_image %>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><%= @product.name %></p>
        <p class="subtitle is-6">$<%= @product.price %></p>
      </div>
    </div>

    <div class="content">
      <%= @product.description %>
      <br>
      Created by <%= @product.user.username %>
    </div>
    <%= link_to 'Buy Now', new_product_order_path(@product), class: 'button is-black', data: {no_turbolink: true} %>
    <%= link_to 'Back', products_path, class: 'button is-black' %>
  </div>
</div>
</div>
</div>
</div>