config/routes.rb
Rails.application.routes.draw do
  resources :orders


  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :users
  resources :products do
    resources :orders
  end
  resources :profiles
  resources :charges

  # as :user do
  #   get '/profile' => 'users/registrations#edit', as: 'edit_user_registration'
  #   patch '/profile' => 'users/registrations#update'
  # end

  get "home/index"
  # get 'market', to: => 'products#index', as: => 'market'

  get '/profile', to:  'profile#index', as: 'user_profile'
  get '/dashboard', to:  'dashboard#index', as: 'dashboard'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar is-black is-fixed-top" role="navigation" aria-label="main navigation">
      <%# <nav class="level"> %>
        <div class="navbar-brand">
          <%= link_to 'BIOS Collective', root_path, class: "navbar-item" %>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "Store", products_path, class: "link is-info" %>
                </p>
                <% if signed_in? %>
                <p class="control">|&ensp;
                  <%= link_to current_user.email, user_profile_path %>
                </p>
                <p class="control">|&ensp;
                  <%= link_to 'Dashboard', dashboard_path if current_user.has_role? :bcmember %>
                </p>
                <p class="control">|&ensp;
                  <%= link_to('Logout', destroy_user_session_path, :method => 'delete') %>
                </p>
                <% else %>
                <p class="control">|&ensp;
                  <%= link_to 'Login', new_user_session_path %>
                </p>
                <p class="control">|&ensp;
                  <%= link_to 'Sign Up', new_user_registration_path %>
                </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <%# </nav> %>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BIOS Collective</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_API_PUBLIC_KEY %>
  </head>

  <body>

  <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>